# Generated by Django 5.1.7 on 2025-03-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_profiles', 'Can view user profiles'), ('can_edit_profiles', 'Can edit user profiles')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
